name = 'shaland'

[build]
cwd = "."
command="bun run build:default"
output="/dist/client"

[vars]
VITE_CLOUDINARY_NAME="dr5gcup5n"
VITE_CLOUDINARY_KEY="492969616715197"
VITE_CLOUDINARY_SECRET="kMyCYOi4FJWKTJADQi_kofl8baM"